### ISSUE TITLE
Chapter 1: Ignored errors prevent from running code examples

### ISSUE THREAD

**Issue by ZapAnton** [Sobeston/ziglearn#100]
Trying to run any code example from Chapter 1 results in an error, for example the following code, saved in the `test.zig` file

```zig
const expect = @import("std").testing.expect;

test "if statement" {
    const a = true;
    var x: u16 = 0;
    if (a) {
        x += 1;
    } else {
        x += 2;
    }
    expect(x == 1);
}
```
produces an error, when compiled via the `zig test test.zig` command

```text
./test.zig:11:11: error: error is ignored. consider using `try`, `catch`, or `if`
    expect(x == 1);
          ^
./test.zig:3:21: note: referenced here
test "if statement" {
                    ^
``` 

Adding `try` before `expect` removes the error message.

zig version: `0.8.0-dev.2237+8eea5eddf`

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/pull/101
