### ISSUE TITLE
Enable HTTP compression

### ISSUE THREAD

**Issue by tleb** [Sobeston/ziglearn#129]
Relying on compression would improve load times, especially for people with a small bandwidth. `gzip` would bring chapter 1 from 143K to 20K for example (the biggest page). Based on the HTTP response headers, Caddy is used. [Its documentation](https://caddyserver.com/docs/caddyfile/directives/encode) indicates that declaring `encode gzip` in the configuration file solves this.

Thanks for this great learning resource!

**Comment by Sobeston** [comment]
Added this line and reloaded, seems to be working now. I thought this was enabled already, good catch!
