### ISSUE TITLE
Chapter 2 section on allocators is out of date

### ISSUE THREAD

**Issue by Eolu** [Sobeston/ziglearn#131]
I'm currently working through this site as my first resource for learning zig (using the latest nightly 0.9 build), and I ran into a compile error when I got here:

```zig
test "fixed buffer allocator" {
    var buffer: [1000]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&buffer);
    var allocator = &fba.allocator;

    const memory = try allocator.alloc(u8, 100);
    defer allocator.free(memory);

    try expect(memory.len == 100);
    try expect(@TypeOf(memory) == []u8);
}
```
The error was this: `type '(bound fn(*std.heap.FixedBufferAllocator) std.mem.Allocator)' does not support field access`, which I found pretty enigmatic as a total newbie to the language. Eventually I was able to get it to work, and it looks like the API for allocators has changed slightly. This is was successful for me:
```zig
test "fixed buffer allocator" {
    var buffer: [1000]u8 = undefined;
    var fba = std.heap.FixedBufferAllocator.init(&buffer);
    const allocator = fba.allocator(); // allocator is a function, not a field

    const memory = try allocator.alloc(u8, 100);
    defer allocator.free(memory);

    try expect(memory.len == 100);
    try expect(@TypeOf(memory) == []u8);
}
```

This error also shows up at least on the "arena allocator" test, I'm unsure if this same issue exists anywhere else throughout.

**Comment by Eolu** [comment]
I went ahead and submitted a [PR](https://github.com/Sobeston/ziglearn/pull/132) for this and another issue. Any further issues I find I'll note in PR form.

**Comment by matu3ba** [comment]
PR was merged, so this should be closed?

**Comment by Eolu** [comment]
Yes
