### ISSUE TITLE
Add reasoning for claim in chapter 1 (const preferred over var)

### ISSUE THREAD

**Issue by Falconerd** [Sobeston/ziglearn#135]
I agree that const should be used rather than var where possible for the simple fact that one can not mistakenly write over data that should stay constant. However, this is just asserted with no reasoning. Perhaps there's another technical reason? I'm not sure.

**Comment by matu3ba** [comment]
There is no good reasoning yet, because the final decision on what to make const and var is still outstanding/discussed without clear guideline/semantic decision being made.

**Comment by deckarep** [comment]
Const is preferred as a best practice these days in favor of immutability. If a declaration is immutable the compiler can typically make optimizations, and additionally you don’t have to be as concerned with data races in multi-threaded scenarios. Immutable data is a good thing so declaring as much data as possible as immutable leads to less bugs overall.
