### ISSUE TITLE
Chapter 1, Slices, second example("slices 2") does not compile

### ISSUE THREAD

**Issue by FlandreScarlet** [Sobeston/ziglearn#14]
Hi, I'm new to Zig and I think I found a (minor) issue with one of your code examples. :)

Chapter 1, Slices, second example("slices 2") does not compile with neither Zig 0.6.0 nor 0.6.0+d907f574e (master at the time of writing).

Here's the complete code example I used:
```zig
const std = @import("std");
const expect = std.testing.expect;

test "slices 2" {
    const array = [_]u8{1, 2, 3, 4, 5};
    const slice = array[0..3];
    expect(@TypeOf(slice) == *[3]u8);
}
```

And here is the output of Zig 0.6.0+d907f574e (0.6.0 has identical output):
```zig
Test [1/1] test "slices 2"...test failure
/home/flandere/local/lib/zig/std/testing.zig:193:14: 0x20448b in std.testing.expect (test)
    if (!ok) @panic("test failure");
             ^
/home/flandere/tmpcode/zig/src/slices.zig:7:11: 0x204aae in test "slices 2" (test)
    expect(@TypeOf(slice) == *[3]u8);
          ^
/home/flandere/local/lib/zig/std/special/test_runner.zig:47:28: 0x22bc0e in std.special.main (test)
        } else test_fn.func();
                           ^
/home/flandere/local/lib/zig/std/start.zig:252:37: 0x20550d in std.start.posixCallMainAndExit (test)
            const result = root.main() catch |err| {
                                    ^
/home/flandere/local/lib/zig/std/start.zig:123:5: 0x20524f in std.start._start (test)
    @call(.{ .modifier = .never_inline }, posixCallMainAndExit, .{});
```

After some fiddling with it, I found out that it expects `*[3]u8` to be `const` because `array` is `const`. 
I made a few attempts to compare slice against a const version of `*[3]u8`, with little success.
These refuse to compile because `const` is invalid in this place:

```zig
expect(@TypeOf(slice) == const *[3]u8);
expect(@TypeOf(slice) == @TypeOf(const *[3]u8));
```

For completeness, the error:
```zig
./src/slices.zig:7:30: error: invalid token: 'const'
    expect(@TypeOf(slice) == const *[3]u8);
                             ^
```
Changing the array to be `var` allows the code to compile, but I'm not sure if it's possible to compare a const slice against a `const *[3]u8`.

Thank you for ziglearn! The first chapter has been a pleasure to read and helps me hit the ground running with learning Zig.

**Comment by Sobeston** [comment]
My apologies - I first wrote this with that being var, but later went to make things const where possible. Mustn't have caught that one - will update now - thanks for the report

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/commit/a975b488b98808a2add6541836dd346926fc2308
