### ISSUE TITLE
Chapter 3 - Build System has incorrect optimization flags.

### ISSUE THREAD

**Issue by SeedyROM** [Sobeston/ziglearn#153]
The text underneath the table of build modes on https://ziglearn.org/chapter-3/ specify a few command line flags for how to set optimizations (eg.) 

> These may be enabled in zig run and zig test with the arguments `-O ReleaseSafe`, `-O ReleaseSmall` and `-O ReleaseFast`.

However the actual compiler optimization flags directly from the compiler help text are these flags:

```
-Drelease-safe=[bool]        Optimizations on and safety on
-Drelease-fast=[bool]        Optimizations on and safety off
-Drelease-small=[bool]       Size optimizations on and safety off
```

Did the flags change recently?

**Comment by sagehane** [comment]
If you look at https://ziglang.org/documentation/0.9.1/#Build-Mode, you will see that `-Drelease-<mode>` is for changing the release modes when compiling with `build.zig`/`zig build`.
```sh-session
$ zig build --help
<omitted
  -Drelease-safe=[bool]        Optimizations on and safety on
  -Drelease-fast=[bool]        Optimizations on and safety off
  -Drelease-small=[bool]       Size optimizations on and safety off
<omitted>
```

For `zig build-exe`, `build-lib`, `build-obj`, and `run`, `-O Release<Mode>` is correct.
```sh-session
$ zig run --help
<omitted>
  -O [mode]                 Choose what to optimize for
    Debug                   (default) Optimizations off, safety on
    ReleaseFast             Optimizations on, safety off
    ReleaseSafe             Optimizations on, safety on
    ReleaseSmall            Optimize for small binary, safety off
<omitted>
```
