### ISSUE TITLE
Chapter 1: incorrect  For loop syntax

### ISSUE THREAD

**Issue by KTheRD** [Sobeston/ziglearn#177]
Chapter 1 has this code:
```zig
for (string, 0..) |character, index| {
    _ = character;
    _ = index;
}
```
Compiler fails to parse with `error: expected ')', found ','`.
Maybe it was meant to be `string[0..]` instead of `string, 0..`.

**Comment by thechampagne** [comment]
This is syntax has introduced in zig 0.11.x

**Comment by KTheRD** [comment]
Oh, thanks. Then maybe marking not yet available features would be good?

**Comment by thechampagne** [comment]
@KTheRD 
In chapter 0: **This guide assumes you’re using a master build** of Zig as opposed to the latest major release, which means downloading a binary from the site or compiling from source; the version of Zig in your package manager is likely outdated. **This guide does not support Zig 0.10.1**

**Comment by KTheRD** [comment]
Thanks, I oversighted that!
