### ISSUE TITLE
Ch. 1 For loop example is not valid code

### ISSUE THREAD

**Issue by stringdom** [Sobeston/ziglearn#179]
The following code used as example of a for loop does not compile on Zig 0.10.0 and therefore is not valid.

    test "for" {
        //character literals are equivalent to integer literals
        const string = [_]u8{ 'a', 'b', 'c' };
    
        for (string, 0..) |character, index| {  // This line gives an error for the compiler expects ')' not a comma ',' after string.
            _ = character;
            _ = index;
        }

The compiler complaints that there cannot be a comma after the string type inside the for loop declaration.

I don't know if this is due to a change that's now valid in nightly 0.11 but it does raises the question, what should the documentation be targeting. The moving nightly or a previous _stable_ version. However not yet very well defined that concept might be right now.

**Comment by Drakx** [comment]
I'm getting the same issue with stable
