### ISSUE TITLE
Use of deprecated @intToPtr in Chapter-1

### ISSUE THREAD

**Issue by akhildevelops** [Sobeston/ziglearn#193]
As per latest zig, `@intToPtr` doesn't exist. Instead, `@ptrFromInt` is available.

[Pointers in Chapter1](https://ziglearn.org/chapter-1/#pointers) still uses deprecated function to convert integer to pointer.

**Comment by Sobeston** [comment]
Thanks for the spot, this one wasn't covered by testing
