### ISSUE TITLE
Suggestions for changes in ziglearn chapter 1

### ISSUE THREAD

**Issue by mrabarnett** [Sobeston/ziglearn#194]
- "when the value before it is an error" => "when the value preceding it is an error"

    It's difficult to parse because "before" is often a conjunction, and "before it is an error" is a valid clause. However, the following words indicate that that reading is incorrect and "before" is, in fact, a preposition.

    Using "preceding" instead of "before" fixes that problem.

- "@enumToInt" => "@intFromEnum"

    There's no builtin called "@enumToInt".

- "Methods can be given to enums. These act as namespaced functions that can be called with dot syntax." => "Enums can be given methods. These act as namespaced functions that can be called with the dot syntax."

    I think the first sentence will read better and that the second sentence needs the definite article.

- "All fields must be given a value." and "Fields may be given defaults:"

    The first part says that all the values are required and the second then basically says that they aren't all required; they're required only where there's no default. Swapping these parts would fix that.

**Comment by Sobeston** [comment]
Thanks for the proofread! I'll send in a commit that fixes this soon

**Comment by Atomk** [comment]
I strongly prefer "given a default value" over "given defaults", it's more explicit.
