### ISSUE TITLE
use in production warning is too authoritative

### ISSUE THREAD

**Issue by andrewrk** [Sobeston/ziglearn#198]
Hi Sobeston,

I was checking out zig.guide today. The website looks really nice.

> Warning: Zig is still pre-1.0; usage in production is still not recommended.

This is an important topic, but let's make sure it is clear whom it is not recommended *by*.

If you are speaking for yourself, you are free to have any opinion you want of course, but please make the readers understand it is your opinion.

If you are speaking for the Zig project, please link to the Zig project leadership making this suggestion (we don't make this suggestion).

**Comment by Sobeston** [comment]
No strong opinions here, this is really just text that's been carried forward in time without much additional thought - it's found inside [ziglearn's first commit](https://github.com/Sobeston/ziglearn/commit/5e93e5945fc786d520cef9d360ad2811e23e1cb1#diff-97396670f241fab0c2a89758127d07f749ce993da566e78087cb884eebf0fbccR10). Use in production makes a ton more sense these days than ~3 years ago, I agree the wording should be softer. Is there anything official I can link to these days on this subject?

**Comment by Atomk** [comment]
This is from [0.11.0 Release Notes](https://ziglang.org/download/0.11.0/release-notes.html#This-Release-Contains-Bugs), section "This Release Contains Bugs":

>Zig has [known bugs](https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+label%3Abug) and even some [miscompilations](https://github.com/ziglang/zig/issues?q=is%3Aopen+is%3Aissue+label%3Amiscompilation).
>
>Zig is immature. Even with Zig 0.11.0, working on a non-trivial project using Zig will likely require participating in the development process.

**Comment by Sobeston** [comment]
Gone ahead and replaced "The latest release of Zig is 0.11; usage in production is not recommended until
1.0." with "The latest release of Zig is 0.11.0 and is currently unstable." in #197. Feel free to reopen if you want to give some more "official" guidance/wording in the future.
