### ISSUE TITLE
ziglearn.org does not match the github version

### ISSUE THREAD

**Issue by Doaxan** [Sobeston/ziglearn#203]
Apparently at the moment it is better to use the github version of ziglearn, in addition to reading the documentation. 

I counted at least 8 differences in [https://ziglearn.org/chapter-1/](https://ziglearn.org/chapter-1/#enums) and [chapter-1.md](https://github.com/Sobeston/ziglearn/blob/master/chapter-1.md), one of them:
https://ziglearn.org/chapter-1/#enums (outdated due to https://github.com/ziglang/zig/pull/16046)

> Enum’s ordinal values start at 0. They can be accessed with the built-in function [@enumToInt](https://ziglang.org/documentation/master/#enumToInt).

https://github.com/Sobeston/ziglearn/blob/master/chapter-1.md#enums

> Enum's ordinal values start at 0. They can be accessed with the built-in function [@intFromEnum](https://ziglang.org/documentation/master/#intFromEnum).

**Comment by Doaxan** [comment]
I didn't notice docusaurus branch, waiting for the release 👍

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/pull/197
