### ISSUE TITLE
Hello World Example Fails to Build

### ISSUE THREAD

**Issue by tmose1106** [Sobeston/ziglearn#36]
I installed Zig 0.6 on my Arch Linux box today. When attempting to build the hello world example in this tutorial, I received the following error.

```
tedm@tedm-arch ~/S/zig_test> zig run main.zig
./main.zig:4:14: error: container 'std.debug' has no member called 'print'
    std.debug.print("Hello, {}!\n", .{"World"});
             ^
```

Looking at the official website, I notice that [their homepage hello world example](https://ziglang.org/#Zig-competes-with-C-instead-of-depending-on-it) calls `warn` instead of `print` and compiles fine. Also, [the official documentation's example](https://ziglang.org/documentation/master/#Hello-World) is quite a bit different, instead writing to stdout.

However, I also see that `print` is [still listed as a method under debug](https://ziglang.org/documentation/master/std/#std;debug.print). Also, the official documentation has an example with the same problem further down called `hello_again.zig`.

**Comment by Sobeston** [comment]
Warn is deprecated, and this guide does not support 0.6.
