### ISSUE TITLE
Async/await

### ISSUE THREAD

**Issue by delaneyj** [Sobeston/ziglearn#45]
I'd love a primer on how to use async/await.  Especially coming from TS/JS/C# where the conventions are different and you have builtin functions like `Promise.(all|race|etc)`

**Comment by Sobeston** [comment]
This is what I'm currently trying to work on, not sure how long it will take

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/commit/445d07c7193776cc53db4b79ff953384e4334950
