### ISSUE TITLE
suggested improvement for the "try" example

### ISSUE THREAD

**Issue by llimllib** [Sobeston/ziglearn#47]
I'm taking zig for a spin, and this explanation and function threw me a bit for a loop, because `try` in this case is exactly equivalent to `return` as far as I can tell:

> try x is a shortcut for x catch |err| return err, and is commonly used in places where handling an error isn't appropriate. Zig's try and catch are unrelated to try-catch in other languages.

```
fn failFn() error{Oops}!void {
    try failingFunction();
}
```

My suggestion would be to give `failFn` a different return type than `failingFunction` so that the `try` cannot be replicated by a `return`. An example I put together would be:

```
const expect = @import("std").testing.expect;

fn failingFunction() error{Oops}!void {
    return error.Oops;
}

test "returning an error" {
    failingFunction() catch |err| {
        expect(err == error.Oops);
        return;
    };
}

fn failFn() error{Oops}!i32 {
    try failingFunction();
    return 12;
}

test "try" {
    var v = failFn() catch |err| {
        expect(err == error.Oops);
        return;
    };
    expect(v == 12); // will never get reached
}
```

Anyway, I'm enjoying the book, I find it very helpful; thank you.

**Comment by Sobeston** [comment]
Agreed, changed in https://github.com/Sobeston/ziglearn/commit/71c54b689cde200f92aa9211c1a4bdef0e48cd46
