### ISSUE TITLE
Unexpected behavior with "naughty pointers" test

### ISSUE THREAD

**Issue by dedifferentiator** [Sobeston/ziglearn#49]
Zig version: `0.6.0+53c63bdb7` on `Linux 5.8.14-arch1-1`

https://ziglearn.org/chapter-1/#pointers

For some reason this code doesn't fail as the block about pointers states:

```
const expect = @import("std").testing.expect;

test "naughty pointer" {
    var x: u16 = 0;
    var y: *u8 = @intToPtr(*u8, x);
}
```
```
$ zig test test.zig
All 1 tests passed.
```

 but after looking closely I noticed that test that fails in the tutorial is named "bad pointer" instead of "naughty pointer",
```
test "bad pointer"...cast causes pointer to be null
.\tests.zig:241:18: 0x7ff69ebb22bd in test "bad pointer" (test.obj)
    var y: *u8 = @intToPtr(*u8, x);
                 ^
```
so I'm a little bit unsure about what's going on. Is this new compiler feature that allows using zero values for pointers? Or something wrong with my zig installation? Or maybe there is a missing test?

**Comment by Sobeston** [comment]
I believe this is a regression in zig and have opened an issue at https://github.com/ziglang/zig/issues/6667

**Comment by Sobeston** [comment]
Seems this is fixed in master zig, closing.
