### ISSUE TITLE
Instructions on adding zig to your path

### ISSUE THREAD

**Issue by Sobeston** [Sobeston/ziglearn#6]

**Comment by linkert** [comment]
Set out to learn zig this evening as my first programing language - felt this was very vague. For Go and Rust, there are clear instructions everywhere.

Anyone care to share the secret? Just make a directory called zig or .zig somewhere in your $HOME and then set it as yet another entry in your $PATH?

**Comment by jessrud** [comment]
@linkert yes. the binary looks for the `lib/` directory based on its own location in the directory tree, so it's enough to simply add the directory that the binary is in to your path. If `lib/` is next to the binary (or in its parent directory, or any ancestor directory), and the binary is in your path, it just works.

For example, I put the contents of the binary archive at `$HOME/.local/opt/zig` and then also add an entry to my PATH environment variable for `$HOME/.local/opt/zig`. You could also put the `zig` binary in `$HOME/.local/bin` and then the contents of `lib/` into `$HOME/.local/lib` and that would work too. The binary is smart enough to find the `lib/` directory whether its right next to the binary, or installed in a normal unixy way.

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/commit/12d505396225084e1a428bf5e74ed05ba8394e37
