### ISSUE TITLE
Typo in Zig version

### ISSUE THREAD

**Issue by Vlad-Shcherbina** [Sobeston/ziglearn#61]
Chapter 0 says:

> This guide does not support the 0.7 build of Zig.

Later it says:

> 3. Verify your install with zig version. The output should be 0.7.0+ followed by some hex digits.

**Comment by Sobeston** [comment]
This is not a typo; ziglearn.org only currently supports master builds of zig; the 0.7 master build will currently work with it but isn't supported as the site will be updated when master does.
