### ISSUE TITLE
Add zig to your path on windows

### ISSUE THREAD

**Issue by clankill3r** [Sobeston/ziglearn#64]
(Constructive feedback, nothing negative here).

This step gave me a lot of problems. In the end you just have to enter the command as one line, but I did not know this. I ended up making a ps1 file. Then I had the problem of running that as administrator. 

Then there was this incorrect answer:
https://superuser.com/questions/108207/how-to-run-a-powershell-script-as-administrator

All by all, it would be worth mentioning that you have to enter the command as one line.

Personally I think this is much easier:

press the windows key on your keyboard, type "envi..."

![environment](https://user-images.githubusercontent.com/738650/101539950-9528e280-399f-11eb-83a6-39fbc8aced04.png)

![env2](https://user-images.githubusercontent.com/738650/101540380-33b54380-39a0-11eb-94a9-045f800e88b0.png)

![env3](https://user-images.githubusercontent.com/738650/101540387-37e16100-39a0-11eb-96ff-71536375ede3.png)

![env4](https://user-images.githubusercontent.com/738650/101540402-3ca61500-39a0-11eb-923e-0a323051f729.png)

Sure this takes more space, but I think it is more user friendly. Maybe you can collapse things in your webdesign?

My 2 cent

**Comment by matu3ba** [comment]
You could make a PR, although PATH differs between OS and describing every OS might not be the nicest thing to do.
Is there a good link that explains this for most major OSes?
