### ISSUE TITLE
Iterators

### ISSUE THREAD

**Issue by Cobertos** [Sobeston/ziglearn#67]
Hey, amazing tutorial! It's already helped me a ton on onboarding (first native language in years tbh).

I've noticed there's no section on iterators. Ziglang has this section [at the bottom of this page](https://ziglang.org#Optional-type-instead-of-null-pointers):

```zig
const std = @import("std");

pub fn main() void {
    const msg = "hello this is dog";
    var it = std.mem.tokenize(msg, " ");
    while (it.next()) |item| {
        std.debug.print("{}\n", .{item});
    }
}
```

...but that's the only place I've found documentation on it so far.

More advanced usage would be nice to. Like, I'm struggling currently iterating over directory entries. The `std.fs.Dir` object emits both error union with an optional, which doesn't play nicely with payload capture without unwrapping the error union with a try first.

```zig
const std = @import("std");

pub fn main() void {
    const cwd = try std.fs.cwd().openDir("", .{ .iterate = true });
    var itr = cwd.iterate();
    while (try itr.next()) |ent| {
        print("{}", .{ ent.name });
    }
}
```

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/commit/b943bfb69102802b8514d9169097c984654c1f70
