### ISSUE TITLE
Values can be ignored by using _ in place of a variable or const declaration.

### ISSUE THREAD

**Issue by clankill3r** [Sobeston/ziglearn#68]
In chapter 1, assignment, https://ziglearn.org/chapter-1/#assignment, there is the following:

> Values can be ignored by using _ in place of a variable or const declaration.

`
_ = 10;`

Can someone give me a more practical example. I don't see how this can be used. I tried multiple things but I only get errors.

**Comment by alexpana** [comment]
```
pub fn doStuff() u32 {
    // do stuff with side effects like printing
    return 10;
}

pub fn main() !void {
    doStuff(); // error: expression value is ignored
    _ = doStuff(); // no error
}
```

If `doStuff` would be a pure function (no side effects, only depends on the inputs) then calling it without using its result would be meaningless.

If `doStuff` has side effects (writes a file, prints to terminal, changes global variables), then calling it without using its result can be a valid use case.

**Comment by clankill3r** [comment]
Ok thanks. I think it would make sense if the example on the ziglearn page would be a bit more clear about this.
