### ISSUE TITLE
"These can be used in anywhere expecting a value."

### ISSUE THREAD

**Issue by clankill3r** [Sobeston/ziglearn#69]
In this chapter:

https://ziglearn.org/chapter-1/#labelled-blocks
There is this sentence:

"These can be used in anywhere expecting a value."

Which I think sounds odd, but I'm not a native english speaker.

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/commit/9c194f3567c06a7947b91e0dbfc4ac1f6d07757d
