### ISSUE TITLE
'std.crypto' has no member called 'randomBytes'

### ISSUE THREAD

**Issue by clankill3r** [Sobeston/ziglearn#73]
https://ziglearn.org/chapter-2/#random-numbers

This:

```zig
test "random numbers" {
    var seed: u64 = undefined;
    try std.crypto.randomBytes(std.mem.asBytes(&seed));
    var rand = std.rand.DefaultPrng.init(seed);

    const a = rand.random.float(f32);
    const b = rand.random.boolean();
    const c = rand.random.int(u8);
    const d = rand.random.intRangeAtMost(u8, 0, 255);
}
```

Does not work for me. I get:

> error: container 'std.crypto' has no member called 'randomBytes'
    try std.crypto.randomBytes(std.mem.asBytes(&seed));

I thought maybe it is `random.bytes` instead of  `randomBytes`, but this gives me other errors, it seems closer to the solution do.

**Comment by Sobeston** [comment]
Thanks!
Closed in https://github.com/Sobeston/ziglearn/commit/37ff0f6eeff5767f001cd0e839dff359b4987ddc
std.crypto.randomBytes until very recently was an alias of std.os.getRandom
