### ISSUE TITLE
{s} outputs zero terminated strings.

### ISSUE THREAD

**Issue by clankill3r** [Sobeston/ziglearn#74]
https://ziglearn.org/chapter-2/#formatting-specifiers

The  last example of formatting in chapter 2 is:

> {s} outputs zero terminated strings.

```zig
test "terminated fmt" {
    var b: [6]u8 = undefined;
    const hello: [*:0]const u8 = "hello!";

    expect(eql(
        u8,
        try bufPrint(&b, "{}", .{hello}),
        "hello!",
    ));
}
```

But `{s}` is never used.

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/commit/223a7c16fc4cbe347ff308e5bf72dad9ef7220d6
