### ISSUE TITLE
const eql = @import("std").mem.eql;

### ISSUE THREAD

**Issue by clankill3r** [Sobeston/ziglearn#75]
In chapter 2 for example, the following is required:

`const eql = @import("std").mem.eql;`

This line comes from chapter 1. I think it is good to repeat this import atleast once on chapter 2 to avoid that people have to backtrack every page in order to get something working.

**Comment by Sobeston** [comment]
closed in https://github.com/Sobeston/ziglearn/commit/5b4d2ff2588bc7c0019d924db01d8a5f274304ef
