### ISSUE TITLE
Explain the concept of payload capture

### ISSUE THREAD

**Issue by Nairou** [Sobeston/ziglearn#81]
In Chapter 1, the "Optionals" section talks about different methods of payload capture.

Coming from languages like C/C++/C#, the phrase "payload capture" was completely foreign to me. I had to figure out what was being described using numerous code examples.

Adding an explanation of what payload capture is, and what value is available in the payload variable, would be helpful to people new to the Zig language.

**Comment by Sobeston** [comment]
Closed in https://github.com/Sobeston/ziglearn/commit/6d4c35987ac62c87d8c2b11dda6392866dca084d.
