### ISSUE TITLE
Move content to a tree structure

### ISSUE THREAD

**Issue by Sobeston** [Sobeston/ziglearn#89]
At the moment everything is in-order, when in reality few will want to read through in its exact ordering.
The front-end should allow people to pick and choose what they want to read next.
Each node should have hints as to its prerequisites.

**Comment by tecanec** [comment]
Chapter 2 is way too long and non-specific. Splitting it up into a "Standard Patterns" folder could help people like [this guy](https://github.com/ziglang/zig/issues/8645) who just want to know how to perform one simple task like allocating a dynamic array by making the right guide easier to find.

**Comment by matu3ba** [comment]
@tecanec Do you have any more concrete ideas?

The main annoyance for me was and partially are the `&[_][]u8` annotations for strings, but other than that everything in std.mem is relative easy to pick up from the tests.
