### ISSUE TITLE
No member named 'signedness' in struct 'std.builtin.Int'

### ISSUE THREAD

**Issue by jtanza** [Sobeston/ziglearn#95]
Ran into an issue when creating a custom Int type from `@typeInfo` in the `GetBiggerInt` func within the [Comptime section of Chapter 1](https://github.com/Sobeston/ziglearn/blob/master/chapter-1.md#comptime): 
```
./hello.zig:312:43: error: no member named 'signedness' in struct 'std.builtin.Int'
            .signedness = @typeInfo(T).Int.signedness,
```

Updating `.signedness` to `.is_signed` fixes the issue for me. 

I am happy to open up a PR to update `.signedness`  =>`.is_signed` in that struct if that is actually an error and I am not just missing something (still a zig noob here). 

Zig Version/ OS Info:
```
jtanza :: projects/zig/hello » zig version                                                                                  
0.7.1
jtanza :: projects/zig/hello » uname -a
Linux jtanza 5.8.7-arch1-1 Sat, 05 Sep 2020 12:31:32 +0000 x86_64 GNU/Linux
```

**Comment by Sobeston** [comment]
Zig changed it from is_signed to signedness somewhere between 0.7.1 and now; this guide only supports the master build of Zig

**Comment by jtanza** [comment]
Ah, my fault now seeing: `"This guide assumes you’re using a master build of Zig as opposed to the latest major release..."` in the guide.

 Sorry about that!
